
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Carneirofc.Scaffold.TermGui.Views {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class InstallersView : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.Label _label;
        
        private Terminal.Gui.TextField _pathTextField;
        
        private Terminal.Gui.Line line;
        
        private Terminal.Gui.ListView _filesListView;
        
        private Terminal.Gui.MenuBar _menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem editMeMenuItem;
        
        private void InitializeComponent() {
            this._menuBar = new Terminal.Gui.MenuBar();
            this._filesListView = new Terminal.Gui.ListView();
            this.line = new Terminal.Gui.Line();
            this._pathTextField = new Terminal.Gui.TextField();
            this._label = new Terminal.Gui.Label();
            this.blueOnBlack = new Terminal.Gui.ColorScheme(new Terminal.Gui.Attribute(4282087679u, 4278979596u), new Terminal.Gui.Attribute(4282087679u, 4294570405u), new Terminal.Gui.Attribute(4282029789u, 4278979596u), new Terminal.Gui.Attribute(4291611852u, 4278979596u), new Terminal.Gui.Attribute(4282029789u, 4294570405u));
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this._label.Width = Dim.Auto();
            this._label.Height = 1;
            this._label.X = 1;
            this._label.Y = 2;
            this._label.Visible = true;
            this._label.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._label.Data = "_label";
            this._label.Text = "Path:";
            this._label.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this._label);
            this._pathTextField.Width = Dim.Fill(0);
            this._pathTextField.Height = 1;
            this._pathTextField.X = 10;
            this._pathTextField.Y = 2;
            this._pathTextField.Visible = true;
            this._pathTextField.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._pathTextField.Secret = false;
            this._pathTextField.Data = "_pathTextField";
            this._pathTextField.Text = "";
            this._pathTextField.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this._pathTextField);
            this.line.Width = Dim.Fill(0);
            this.line.Height = 2;
            this.line.X = 0;
            this.line.Y = 3;
            this.line.Visible = true;
            this.line.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this.line.Data = "line";
            this.line.Text = "";
            this.line.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Add(this.line);
            this._filesListView.Width = Dim.Fill(0);
            this._filesListView.Height = Dim.Auto();
            this._filesListView.X = -1;
            this._filesListView.Y = 4;
            this._filesListView.Visible = false;
            this._filesListView.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._filesListView.Data = "_filesListView";
            this._filesListView.TextAlignment = Terminal.Gui.Alignment.Start;
            this._filesListView.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this._filesListView.AllowsMarking = true;
            this._filesListView.AllowsMultipleSelection = true;
            this.Add(this._filesListView);
            this._menuBar.Width = Dim.Fill(0);
            this._menuBar.Height = 1;
            this._menuBar.X = 0;
            this._menuBar.Y = 0;
            this._menuBar.Visible = true;
            this._menuBar.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._menuBar.Data = "_menuBar";
            this._menuBar.TextAlignment = Terminal.Gui.Alignment.Start;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.editMeMenuItem = new Terminal.Gui.MenuItem();
            this.editMeMenuItem.Title = "Edit Me";
            this.editMeMenuItem.Data = "editMeMenuItem";
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.editMeMenuItem};
            this._menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu};
            this.Add(this._menuBar);
        }
    }
}
